controller_manager:
  ros__parameters:
    update_rate: 30

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: forward_command_controller/ForwardCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


arm_controller:
  ros__parameters:
    joints:
      - Fixed_Base_rot_1
      - Rotary_Base_rot_2
      - BC_Connecting_Rod_rot_3

    command_interfaces:
      - position
    state_interfaces:
      - position
    open_loop_control: true
    allow_integration_in_goal_trajectories: true


gripper_controller:
  ros__parameters:
    joints:
      - Jaw_Bracket_rot_6
    # - Jaw_Bracket_rot_9
    # command_interfaces:
    #   - position
    # state_interfaces:
    #   - position
    interface_name: position
    
