# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  BC_Connecting_Rod_rot_3:
    has_velocity_limits: true
    max_velocity: 1000000.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  Fixed_Base_rot_1:
    has_velocity_limits: true
    max_velocity: 1000000.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  Jaw_Bracket_rot_6:
    has_velocity_limits: true
    max_velocity: 1000000.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  Jaw_Bracket_rot_9:
    has_velocity_limits: true
    max_velocity: 1000000.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  Rotary_Base_rot_2:
    has_velocity_limits: true
    max_velocity: 1000000.0
    has_acceleration_limits: false
    max_acceleration: 0.0